# Generated by Django 4.2.6 on 2023-10-27 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_weeklytaskstats_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 7, 58, 21, 769294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='weeklytaskstats',
            name='total_assigned_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklytaskstats',
            name='total_completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklytaskstats',
            name='total_pending_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
