# Generated by Django 4.2.6 on 2023-10-27 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_created_at_task_created_at_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 10, 1, 32, 821707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at_week',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 10, 1, 32, 821618, tzinfo=datetime.timezone.utc)),
        ),
    ]
